#  Oracle DataSource 
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=TEST
spring.datasource.password=Test_1234

#  SQL init 
spring.sql.init.mode=always
spring.sql.init.separator=@@
spring.sql.init.schema-locations=classpath:db/oracle/schema.sql
spring.sql.init.data-locations=classpath:db/oracle/data.sql
