MERGE INTO EMPLOYEES (ID, NAME, SALARY) KEY (ID) VALUES (1, 'Alice', 75000.00)
@@
MERGE INTO EMPLOYEES (ID, NAME, SALARY) KEY (ID) VALUES (2, 'Bob',   82000.00)
@@
MERGE INTO EMPLOYEES (ID, NAME, SALARY) KEY (ID) VALUES (3, 'Carol', 91500.00)
@@